# Generated by Django 5.0 on 2025-12-30 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Maç Tarihi')),
                ('team1_score', models.IntegerField(default=0, verbose_name='Takım 1 Skor')),
                ('team2_score', models.IntegerField(default=0, verbose_name='Takım 2 Skor')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Maç Bitti mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='teams.team', verbose_name='Takım 1')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='teams.team', verbose_name='Takım 2')),
            ],
            options={
                'verbose_name': 'Maç',
                'verbose_name_plural': 'Maçlar',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PlayerMatchStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.IntegerField(default=0, verbose_name='Gol Sayısı')),
                ('assists', models.IntegerField(default=0, verbose_name='Asist Sayısı')),
                ('played', models.BooleanField(default=True, verbose_name='Oynadı mı?')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='matches.match', verbose_name='Maç')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_stats', to='players.player', verbose_name='Oyuncu')),
                ('team', models.ForeignKey(help_text='Oyuncunun bu maçta oynadığı takım (transfer geçmişi için)', on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Oynadığı Takım')),
            ],
            options={
                'verbose_name': 'Oyuncu Maç İstatistiği',
                'verbose_name_plural': 'Oyuncu Maç İstatistikleri',
                'ordering': ['-match__date'],
                'unique_together': {('match', 'player')},
            },
        ),
    ]
