# Generated by Django 5.0 on 2026-02-04 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '__first__'),
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='leagues.league', verbose_name='Lig'),
        ),
        migrations.AddField(
            model_name='match',
            name='week',
            field=models.IntegerField(blank=True, null=True, verbose_name='Hafta'),
        ),
    ]
