# Generated by Django 5.0 on 2026-02-05 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_week_standing'),
        ('matches', '0002_match_league_match_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='league',
        ),
        migrations.AlterField(
            model_name='match',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='leagues.week', verbose_name='Hafta'),
        ),
    ]
