# Generated by Django 5.0 on 2026-02-11 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_remove_match_league_alter_match_week'),
        ('players', '0006_player_jersey_number_player_preferred_foot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_score_editable',
            field=models.BooleanField(default=False, help_text='Hakem skoru ve istatistikleri düzenleyebilir mi?', verbose_name='Skor Girilebilir mi?'),
        ),
        migrations.AddField(
            model_name='match',
            name='referee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refereed_matches', to=settings.AUTH_USER_MODEL, verbose_name='Hakem'),
        ),
        migrations.AddField(
            model_name='playermatchstats',
            name='red_cards',
            field=models.IntegerField(default=0, verbose_name='Kırmızı Kart'),
        ),
        migrations.AddField(
            model_name='playermatchstats',
            name='yellow_cards',
            field=models.IntegerField(default=0, verbose_name='Sarı Kart'),
        ),
        migrations.CreateModel(
            name='PlayerMatchRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_pace', models.IntegerField(default=5, verbose_name='Hız (PAC)')),
                ('rating_shooting', models.IntegerField(default=5, verbose_name='Şut (SHO)')),
                ('rating_passing', models.IntegerField(default=5, verbose_name='Pas (PAS)')),
                ('rating_dribbling', models.IntegerField(default=5, verbose_name='Top Sürme (DRI)')),
                ('rating_defense', models.IntegerField(default=5, verbose_name='Defans (DEF)')),
                ('rating_physical', models.IntegerField(default=5, verbose_name='Fizik (PHY)')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Yorum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='matches.match', verbose_name='Maç')),
                ('rated_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to='players.player', verbose_name='Oylanan')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to='players.player', verbose_name='Oylayan')),
            ],
            options={
                'verbose_name': 'Oyuncu Değerlendirmesi',
                'verbose_name_plural': 'Oyuncu Değerlendirmeleri',
                'ordering': ['-created_at'],
                'unique_together': {('match', 'rater', 'rated_player')},
            },
        ),
    ]
