# Generated by Django 5.0 on 2026-02-16 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_match_is_score_editable_match_referee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermatchrating',
            name='rating_diving',
            field=models.IntegerField(default=5, verbose_name='Uçma (DIV)'),
        ),
        migrations.AddField(
            model_name='playermatchrating',
            name='rating_handling',
            field=models.IntegerField(default=5, verbose_name='Elle Kontrol (HAN)'),
        ),
        migrations.AddField(
            model_name='playermatchrating',
            name='rating_kicking',
            field=models.IntegerField(default=5, verbose_name='Ayak (KIC)'),
        ),
        migrations.AddField(
            model_name='playermatchrating',
            name='rating_positioning',
            field=models.IntegerField(default=5, verbose_name='Yer Tutma (POS)'),
        ),
        migrations.AddField(
            model_name='playermatchrating',
            name='rating_reflexes',
            field=models.IntegerField(default=5, verbose_name='Refleks (REF)'),
        ),
        migrations.AddField(
            model_name='playermatchrating',
            name='rating_speed',
            field=models.IntegerField(default=5, verbose_name='Hız (SPD)'),
        ),
    ]
