# Generated by Django 5.0 on 2026-02-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_playermatchrating_rating_diving_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Zamanı'),
        ),
    ]
