# Generated by Django 5.0 on 2026-02-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_match_finished_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_live',
            field=models.BooleanField(default=False, verbose_name='Canlı mı?'),
        ),
    ]
