# Generated by Django 5.0 on 2026-04-19 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_match_is_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_type',
            field=models.CharField(choices=[('LEAGUE', 'Lig Maçı'), ('TOURNAMENT', 'Turnuva Maçı')], default='LEAGUE', max_length=20, verbose_name='Maç Tipi'),
        ),
    ]
