# Generated by Django 5.0 on 2026-04-25 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_alter_match_team1_alter_match_team2'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team1_penalties',
            field=models.IntegerField(blank=True, null=True, verbose_name='Takım 1 Penaltı'),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_penalties',
            field=models.IntegerField(blank=True, null=True, verbose_name='Takım 2 Penaltı'),
        ),
    ]
