# Generated by Django 5.0 on 2025-12-27 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Takım Adı')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team_logos/', verbose_name='Takım Logosu')),
                ('wins', models.IntegerField(default=0, verbose_name='Kazanılan Maçlar')),
                ('losses', models.IntegerField(default=0, verbose_name='Kaybedilen Maçlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Takım',
                'verbose_name_plural': 'Takımlar',
                'ordering': ['-wins', 'name'],
            },
        ),
    ]
