# Generated by Django 5.0 on 2025-12-30 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_player_photo'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='captain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captain_of', to='players.player', verbose_name='Kaptan'),
        ),
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Bekliyor'), ('ACCEPTED', 'Kabul Edildi'), ('REJECTED', 'Reddedildi')], default='PENDING', max_length=10, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to='players.player', verbose_name='Oyuncu')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to='teams.team', verbose_name='Takım')),
            ],
            options={
                'verbose_name': 'Transfer İsteği',
                'verbose_name_plural': 'Transfer İstekleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
