# Generated by Django 5.0 on 2025-12-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_captain_transferrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-points', '-goals_scored', 'name'], 'verbose_name': 'Takım', 'verbose_name_plural': 'Takımlar'},
        ),
        migrations.AddField(
            model_name='team',
            name='draws',
            field=models.IntegerField(default=0, verbose_name='Beraberlikler'),
        ),
        migrations.AddField(
            model_name='team',
            name='goals_conceded',
            field=models.IntegerField(default=0, verbose_name='Yenen Goller'),
        ),
        migrations.AddField(
            model_name='team',
            name='goals_scored',
            field=models.IntegerField(default=0, verbose_name='Atılan Goller'),
        ),
        migrations.AddField(
            model_name='team',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Puan'),
        ),
    ]
