# Generated by Django 5.0 on 2026-02-05 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_team_options_team_draws_team_goals_conceded_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name'], 'verbose_name': 'Takım', 'verbose_name_plural': 'Takımlar'},
        ),
        migrations.RemoveField(
            model_name='team',
            name='draws',
        ),
        migrations.RemoveField(
            model_name='team',
            name='goals_conceded',
        ),
        migrations.RemoveField(
            model_name='team',
            name='goals_scored',
        ),
        migrations.RemoveField(
            model_name='team',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='team',
            name='points',
        ),
        migrations.RemoveField(
            model_name='team',
            name='wins',
        ),
    ]
