# Generated by Django 5.0 on 2026-02-05 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Lig Adı')),
                ('season', models.CharField(help_text='Örn: 2024-2025', max_length=50, verbose_name='Sezon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Lig')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Lig',
                'verbose_name_plural': 'Ligler',
                'ordering': ['-created_at'],
            },
        ),
    ]
