# Generated by Django 5.0 on 2026-02-05 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
        ('teams', '0004_alter_team_options_remove_team_draws_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Hafta Adı')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('is_played', models.BooleanField(default=False, verbose_name='Oynandı mı?')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='leagues.league', verbose_name='Lig')),
            ],
            options={
                'verbose_name': 'Hafta',
                'verbose_name_plural': 'Haftalar',
                'ordering': ['league', 'start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.IntegerField(default=0, verbose_name='Oynanan')),
                ('wins', models.IntegerField(default=0, verbose_name='Galibiyet')),
                ('draws', models.IntegerField(default=0, verbose_name='Beraberlik')),
                ('losses', models.IntegerField(default=0, verbose_name='Mağlubiyet')),
                ('goals_for', models.IntegerField(default=0, verbose_name='Atılan Gol')),
                ('goals_against', models.IntegerField(default=0, verbose_name='Yenen Gol')),
                ('points', models.IntegerField(default=0, verbose_name='Puan')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='leagues.league', verbose_name='Lig')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_standings', to='teams.team', verbose_name='Takım')),
            ],
            options={
                'verbose_name': 'Puan Durumu',
                'verbose_name_plural': 'Puan Durumları',
                'ordering': ['-points', '-goals_for'],
                'unique_together': {('league', 'team')},
            },
        ),
    ]
