# Generated by Django 5.0 on 2026-04-20 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_week_standing'),
        ('matches', '0008_match_match_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Final Turnuvası', max_length=100, verbose_name='Turnuva Adı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('league', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tournament', to='leagues.league', verbose_name='Lig')),
            ],
            options={
                'verbose_name': 'Turnuva',
                'verbose_name_plural': 'Turnuvalar',
            },
        ),
        migrations.CreateModel(
            name='TournamentMatch',
            fields=[
                ('match_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='matches.match')),
                ('round_name', models.CharField(help_text='Örn: Çeyrek Final', max_length=50, verbose_name='Tur Adı')),
                ('round_index', models.IntegerField(default=0, help_text='0: İlk Tur, 1: İkinci Tur vb.', verbose_name='Tur Sırası')),
                ('position', models.IntegerField(default=0, help_text='Aynı turdaki maçların yukarıdan aşağıya sırası', verbose_name='Sıralama Pozisyonu')),
                ('next_match', models.ForeignKey(blank=True, help_text='Bu maçın kazananı hangi maça gidecek?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_matches', to='leagues.tournamentmatch', verbose_name='Sonraki Maç')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_matches', to='leagues.tournament', verbose_name='Turnuva')),
            ],
            options={
                'verbose_name': 'Turnuva Maçı',
                'verbose_name_plural': 'Turnuva Maçları',
                'ordering': ['round_index', 'position'],
            },
            bases=('matches.match',),
        ),
    ]
