# Generated by Django 5.0 on 2025-12-30 16:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Görünen Ad')),
                ('age', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(60)], verbose_name='Yaş')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='player_photos/', verbose_name='Fotoğraf')),
                ('position', models.CharField(choices=[('KL', 'Kaleci'), ('SLB', 'Sol Bek'), ('SĞB', 'Sağ Bek'), ('STP', 'Stoper'), ('MO', 'Merkez Orta Saha'), ('MOO', 'Merkez Ofansif Orta Saha'), ('SLK', 'Sol Kanat'), ('SĞK', 'Sağ Kanat'), ('ST', 'Santrafor')], default='ST', max_length=3, verbose_name='Pozisyon')),
                ('pace', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Hız (PAC)')),
                ('shooting', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Şut (SHO)')),
                ('passing', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Pas (PAS)')),
                ('dribbling', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Dribling (DRI)')),
                ('defense', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Defans (DEF)')),
                ('physical', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Fizik (PHY)')),
                ('diving', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Uçma (DIV)')),
                ('handling', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Elle Kontrol (HAN)')),
                ('kicking', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Degaj (KIC)')),
                ('reflexes', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Refleks (REF)')),
                ('speed', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Hız (SPD)')),
                ('positioning', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Yer Tutma (POS)')),
                ('overall', models.IntegerField(default=50, editable=False, verbose_name='Overall')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='teams.team', verbose_name='Güncel Takım')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Oyuncu',
                'verbose_name_plural': 'Oyuncular',
                'ordering': ['-overall', 'name'],
            },
        ),
    ]
