# Generated by Django 5.0 on 2025-12-27 23:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Oyuncu Adı')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(50)], verbose_name='Yaş')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='player_photos/', verbose_name='Fotoğraf')),
                ('overall', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Overall')),
                ('pace', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Hız (PAC)')),
                ('shooting', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Şut (SHO)')),
                ('passing', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Pas (PAS)')),
                ('dribbling', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Dribling (DRI)')),
                ('defense', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Defans (DEF)')),
                ('physical', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Fizik (PHY)')),
                ('position', models.CharField(default='ST', help_text='Örn: ST, LW, CM, CB', max_length=3, verbose_name='Pozisyon')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('current_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='teams.team', verbose_name='Güncel Takım')),
            ],
            options={
                'verbose_name': 'Oyuncu',
                'verbose_name_plural': 'Oyuncular',
                'ordering': ['-overall', 'name'],
            },
        ),
    ]
