# Generated by Django 5.0 on 2025-12-30 16:52

import players.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=players.models.secure_file_upload, verbose_name='Fotoğraf'),
        ),
    ]
