# Generated by Django 5.0 on 2025-12-31 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_player_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('KL', 'Kaleci'), ('SLB', 'Sol Bek'), ('SGB', 'Sağ Bek'), ('STP', 'Stoper'), ('MO', 'Merkez Orta Saha'), ('MOO', 'Merkez Ofansif Orta Saha'), ('SLK', 'Sol Kanat'), ('SGK', 'Sağ Kanat'), ('ST', 'Santrafor')], default='ST', max_length=3, verbose_name='Pozisyon'),
        ),
    ]
