# Generated by Django 5.0 on 2026-01-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_alter_player_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_email_verified',
            field=models.BooleanField(default=False, verbose_name='E-posta Doğrulandı mı?'),
        ),
        migrations.AddField(
            model_name='player',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Doğrulama Kodu'),
        ),
    ]
