# Generated by Django 5.0 on 2026-01-02 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_player_is_email_verified_player_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='verification_code_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Kod Oluşturulma Tarihi'),
        ),
    ]
