# Generated by Django 5.0 on 2026-01-05 06:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_player_verification_code_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='jersey_number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Forma Numarası'),
        ),
        migrations.AddField(
            model_name='player',
            name='preferred_foot',
            field=models.CharField(choices=[('right', 'Sağ'), ('left', 'Sol'), ('both', 'Her İkisi')], default='right', max_length=10, verbose_name='Ayak Tercihi'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('KL', 'Kaleci'), ('SLB', 'Sol Bek'), ('SGB', 'Sağ Bek'), ('STP', 'Stoper'), ('DOS', 'Defansif Orta Saha'), ('MO', 'Merkez Orta Saha'), ('MOO', 'Merkez Ofansif Orta Saha'), ('SLK', 'Sol Kanat'), ('SGK', 'Sağ Kanat'), ('ST', 'Santrafor')], default='ST', max_length=3, verbose_name='Pozisyon'),
        ),
    ]
