# Generated by Django 5.0 on 2026-02-16 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_player_jersey_number_player_preferred_foot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rating_count',
            field=models.IntegerField(default=0, verbose_name='Oylanma Sayısı'),
        ),
        migrations.AddField(
            model_name='player',
            name='total_rating_defense',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_rating_diving',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_rating_dribbling',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_rating_handling',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_rating_kicking',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_rating_pace',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_rating_passing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_rating_physical',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_rating_positioning',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_rating_reflexes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_rating_shooting',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_rating_speed',
            field=models.IntegerField(default=0),
        ),
    ]
