# Generated by Django 5.0 on 2025-12-31 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('notification_type', models.CharField(choices=[('TEAM_REQUEST', 'Takım İsteği'), ('TEAM_RESPONSE', 'Takım Yanıtı'), ('SYSTEM', 'Sistem Mesajı')], default='SYSTEM', max_length=20, verbose_name='Bildirim Tipi')),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu mu?')),
                ('related_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='İlgili Link')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Alıcı')),
            ],
            options={
                'verbose_name': 'Bildirim',
                'verbose_name_plural': 'Bildirimler',
                'ordering': ['-created_at'],
            },
        ),
    ]
