# Generated by Django 5.0 on 2026-01-03 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='Yeni Bildirim', max_length=255, verbose_name='Başlık'),
        ),
    ]
